name: Update NEW README

on:
  push:
    branch: main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install
        run: npm ci
      - name: Update README
        run: node ./create-directory.js
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "grewer@grewer.cn"
          git config --global user.name "grewer"
          git pull
          git add -A
          git commit -m "Updated content" || exit 0
          git push
